name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          command-prefix: 'percy exec -- npx'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
