name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          command-prefix: 'percy exec -- npx'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
          CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
