name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    name: E2E on Chrome
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          command-prefix: 'percy exec -- npx'
        env:
          PURGE_CSS: true
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
          CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
