name: Size Change Report

on:
  pull_request:
    branches: [master]

jobs:
  pkg-size-report:
    name: Size Change Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Size Change Report
        uses: pkg-size/action@v1
        with:
          build-command: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
